### PR TITLE
[ENH] Function for converting PAG to MAG

### LINKED ISSUE #85: Convert MAG to PAG
**Is your feature request related to a problem? Please describe.**
A MAG is a mixed-edge graph with directed and bidirected edges and has the 'maximality' property. 

This is a sub-procedure of https://github.com/py-why/pywhy-graphs/pull/73 and will enable that to function properly.

**Describe the solution you'd like**
Implement a function `mag_to_pag`, which takes in a valid MAG and outputs the corresponding PAG.

**Additional context**
@aryan26roy if you're still interested, this can be the next step before revisiting #73.

### PR DESCRIPTION
**Pull request by aryan26roy**
Closes #85

Changes proposed in this pull request:

- Adds a function for converting PAGs to MAGs.

## Before submitting

- [ ] I've read and followed all steps in the [Making a pull request](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [ ] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [ ] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

## After submitting

- [ ] All GitHub Actions jobs for my pull request have passed.

### CODE REVIEW

**Comment by adam2392** [comment]
I think you want a function that goes MAG to PAG? 

A PAG has many MAGs possibly associated with it.

**Comment by aryan26roy** [comment]
Ah ok. This for after the MAG has been validated in #73.

**Comment by adam2392** [comment]
Can you describe the algorithm in the PR description?

**Comment by aryan26roy** [comment]
@adam2392 moving the discussion to #87

**Pull request closed without merging**
